#!/usr/bin/env bash
#
# Generates nsjail-seccomp.json and gvisor-seccomp.json from the upstream
# Docker default seccomp profile plus Retool-specific additions.
#
# Both profiles use the same pattern:
#   Docker default (as-is) + unconditional ALLOW rules inserted before the
#   capability-gated section so they take BPF precedence.
#
# Usage:
#   ./generate.sh           # fetch upstream + generate both profiles
#   ./generate.sh --check   # generate to temp dir + diff against checked-in files
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${SCRIPT_DIR}/../files"

# ---------------------------------------------------------------------------
# Upstream Docker default seccomp profile pin
# ---------------------------------------------------------------------------
UPSTREAM_REPO="moby/profiles"
UPSTREAM_COMMIT="61eaf32614c7c71b60bd8927d3e6a4ffc8ff1f31"
UPSTREAM_URL="https://raw.githubusercontent.com/${UPSTREAM_REPO}/${UPSTREAM_COMMIT}/seccomp/default.json"

CACHE_FILE="${SCRIPT_DIR}/.docker-default-seccomp-${UPSTREAM_COMMIT}.json"

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
check_deps() {
  for cmd in curl jq; do
    if ! command -v "$cmd" &>/dev/null; then
      echo "ERROR: $cmd is required but not installed." >&2
      exit 1
    fi
  done
}

fetch_upstream() {
  if [[ ! -f "$CACHE_FILE" ]]; then
    echo "Fetching Docker default seccomp profile from ${UPSTREAM_REPO}@${UPSTREAM_COMMIT:0:12}..." >&2
    curl -fsSL "$UPSTREAM_URL" -o "$CACHE_FILE"
  else
    echo "Using cached Docker default: ${CACHE_FILE}" >&2
  fi
}

# insert_rules <input.json> <additions.json> <output.json>
#
# Takes Docker default, inserts the rules from additions.json right before
# the first CAP_SYS_ADMIN-gated rule (so unconditional rules take BPF
# precedence over the conditional clone3-ERRNO and capability-gated rules
# that follow).
insert_rules() {
  local input="$1" additions="$2" dest="$3" comment="$4"
  jq --slurpfile add "$additions" --arg comment "$comment" '
    ($add[0]) as $new_rules |
    (.syscalls | to_entries
      | map(select(.value.includes.caps // [] | index("CAP_SYS_ADMIN")))
      | .[0].key) as $idx |
    {comment: $comment} + . |
    .syscalls = .syscalls[:$idx] + $new_rules + .syscalls[$idx:]
  ' "$input" > "$dest"
}

# ---------------------------------------------------------------------------
# nsjail: Docker default + 6 syscalls for nsjail sandboxing
# ---------------------------------------------------------------------------
generate_nsjail() {
  local dest="$1"
  echo "Generating nsjail-seccomp.json..." >&2

  local additions
  additions="$(mktemp)"
  cat > "$additions" <<'JSON'
[
  {
    "names": ["clone", "clone2", "mount", "pivot_root", "sethostname", "umount2"],
    "action": "SCMP_ACT_ALLOW",
    "comment": "nsjail sandboxing: unprivileged user-namespace creation, mount/pivot_root for jail filesystem, sethostname for UTS namespace"
  }
]
JSON

  local comment="Based on Docker default seccomp profile from ${UPSTREAM_REPO} (https://github.com/${UPSTREAM_REPO}/blob/${UPSTREAM_COMMIT}/seccomp/default.json). Generated by charts/retool/seccomp/generate.sh"
  insert_rules "$CACHE_FILE" "$additions" "$dest" "$comment"
  rm -f "$additions"
}

# ---------------------------------------------------------------------------
# gVisor: Docker default + header tweaks + 19 syscalls for gVisor/pasta
# ---------------------------------------------------------------------------
generate_gvisor() {
  local dest="$1"
  echo "Generating gvisor-seccomp.json..." >&2

  local additions
  additions="$(mktemp)"
  cat > "$additions" <<'JSON'
[
  {
    "names": ["clone", "clone3", "setns", "unshare"],
    "action": "SCMP_ACT_ALLOW",
    "comment": "gVisor + pasta: namespace creation and entry (CLONE_NEW* flags, setns to join)"
  },
  {
    "names": ["sethostname"],
    "action": "SCMP_ACT_ALLOW",
    "comment": "pasta: set hostname inside namespace"
  },
  {
    "names": ["mount", "umount2"],
    "action": "SCMP_ACT_ALLOW",
    "comment": "gVisor: sandbox filesystem setup (tmpfs, proc, bind mounts)"
  },
  {
    "names": ["fsconfig", "fsmount", "fsopen", "fspick", "mount_setattr", "move_mount", "open_tree"],
    "action": "SCMP_ACT_ALLOW",
    "comment": "gVisor: new mount API (kernel 5.2+) for overlay root filesystem setup"
  },
  {
    "names": ["pivot_root"],
    "action": "SCMP_ACT_ALLOW",
    "comment": "gVisor: filesystem root isolation for sentry and gofer"
  },
  {
    "names": ["ptrace"],
    "action": "SCMP_ACT_ALLOW",
    "comment": "gVisor systrap platform: workload executor thread init"
  },
  {
    "names": ["io_uring_enter", "io_uring_register", "io_uring_setup"],
    "action": "SCMP_ACT_ALLOW",
    "comment": "gVisor: async I/O for gofer and application workloads"
  }
]
JSON

  # Start from Docker default, patch header fields, then insert additions
  local patched
  patched="$(mktemp)"
  jq '
    .defaultErrnoRet = 38 |
    .archMap = [
      {"architecture": "SCMP_ARCH_X86_64", "subArchitectures": ["SCMP_ARCH_X86", "SCMP_ARCH_X32"]},
      {"architecture": "SCMP_ARCH_AARCH64", "subArchitectures": ["SCMP_ARCH_ARM"]}
    ]
  ' "$CACHE_FILE" > "$patched"

  local comment="Based on Docker default seccomp profile from ${UPSTREAM_REPO} (https://github.com/${UPSTREAM_REPO}/blob/${UPSTREAM_COMMIT}/seccomp/default.json). Generated by charts/retool/seccomp/generate.sh — defaultErrnoRet changed to ENOSYS (38), archMap narrowed to x86_64 + aarch64 (gVisor supported platforms)."
  insert_rules "$patched" "$additions" "$dest" "$comment"
  rm -f "$patched" "$additions"
}

# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
check_deps
fetch_upstream

if [[ "${1:-}" == "--check" ]]; then
  tmpdir="$(mktemp -d)"
  trap 'rm -rf "$tmpdir"' EXIT

  generate_nsjail "${tmpdir}/nsjail-seccomp.json"
  generate_gvisor "${tmpdir}/gvisor-seccomp.json"

  rc=0
  for f in nsjail-seccomp.json gvisor-seccomp.json; do
    if ! diff -u "${OUTPUT_DIR}/${f}" "${tmpdir}/${f}"; then
      echo "MISMATCH: ${f} is out of date. Run charts/retool/seccomp/generate.sh to regenerate." >&2
      rc=1
    else
      echo "OK: ${f} is up to date." >&2
    fi
  done
  exit "$rc"
else
  generate_nsjail "${OUTPUT_DIR}/nsjail-seccomp.json"
  generate_gvisor "${OUTPUT_DIR}/gvisor-seccomp.json"
  echo "Done. Profiles written to ${OUTPUT_DIR}/" >&2
fi
