{{- if eq (include "retool.appArmorNsjailInstaller.enabled" .) "1" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "retool.fullname" . }}-apparmor-nsjail
  labels:
    {{- include "retool.codeExecutor.labels" . | nindent 4 }}
    {{- include "retool.labels" . | nindent 4 }}
    app.kubernetes.io/component: apparmor-installer
data:
  usr.bin.nsjail: |
    profile /usr/bin/nsjail flags=(unconfined) {
       userns,
    }
  retool-executor: |
    #include <tunables/global>

    profile retool-executor flags=(attach_disconnected,mediate_deleted) {
      #include <abstractions/base>

      network,
      capability,
      file,
      umount,
      mount,
      pivot_root,
      userns,

      signal (send,receive) peer=retool-executor,
      signal (receive) peer=unconfined,

      ptrace (trace,read,tracedby,readby) peer=retool-executor,

      deny @{PROC}/* w,
      deny @{PROC}/sys/[^k]*/** wklx,
      deny @{PROC}/sys/kernel/{?,??,[^s][^h][^m]**} wklx,
      deny @{PROC}/sysrq-trigger rwklx,
      deny @{PROC}/kcore rwklx,

      deny /sys/[^f]*/** wklx,
      deny /sys/f[^s]*/** wklx,
      deny /sys/fs/[^c]*/** wklx,
      deny /sys/fs/c[^g]*/** wklx,
      deny /sys/fs/cg[^r]*/** wklx,
      deny /sys/firmware/** rwklx,
      deny /sys/devices/virtual/powercap/** rwklx,
      deny /sys/kernel/security/** rwklx,
    }
{{- end }}
