{{- if include "retool.workflows.enabled" . }}
{{- /* TEMP(PLAT-1012 TEST BRANCH): >=1.33 version gate removed to force the seccomp path on a <1.33 cluster for testing. DO NOT MERGE. */ -}}
{{- if (not .Values.codeExecutor.securityContext) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "retool.fullname" . }}-code-executor-seccomp
  labels:
    {{- include "retool.labels" . | nindent 4 }}
data:
  nsjail-seccomp.json: |
    {{- .Files.Get "files/nsjail-seccomp.json" | nindent 4 }}
{{- end }}
{{- end }}
