{{- if eq (include "retool.rr.componentEnabled" (dict "root" $ "component" "jsExecutor")) "1" }}
{{- if .Values.rr.jsExecutor.installSeccompProfile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "retool.fullname" . }}-js-executor-seccomp
  labels:
    {{- include "retool.labels" . | nindent 4 }}
data:
  nsjail-seccomp.json: |
    {{- .Files.Get "files/nsjail-seccomp.json" | nindent 4 }}
{{- end }}
{{- end }}
