apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "retool.fullname" . }}-js-executor-seccomp
  labels:
    {{- include "retool.labels" . | nindent 4 }}
data:
  nsjail-seccomp.json: |
    {{- .Files.Get "files/nsjail-seccomp.json" | nindent 4 }}
