{{- if $.Values.jsExecutorDefault.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: js-executor-seccomp
data:
  nsjail-seccomp.json: |
    {{- .Files.Get "files/nsjail-seccomp.json" | nindent 4 }}
{{- end }}
