{{ include "retool.worker.deployment" (dict "context" . "worker" (dict 
  "enabled" (include "retool.agents.enabled" .)
  "name" (include "retool.agentEvalWorker.name" .)
  "selectorLabels" (include "retool.agentEvalWorker.selectorLabels" .)
  "labels" (include "retool.agentEvalWorker.labels" .)
  "containerName" "agent-eval-worker"
  "serviceType" "AGENT_EVAL_TEMPORAL_WORKER"
  "taskqueue" "agent-eval"
  "replicaCount" ((.Values.agents.evalWorker).replicaCount | default (.Values.agents.replicaCount | default 1))
  "resources" .Values.agents.evalWorker.resources
  "annotations" .Values.agents.annotations
  "nodeOptions" ((.Values.agents.config).nodeOptions | default "--max_old_space_size=1024")
  "healthcheckPort" "3012"
  "metricsPort" "9090"
  "prometheusAnnotations" true
  "config" .Values.agents.config
  "dbConnectorTimeout" .Values.agents.dbConnectorTimeout
  "temporalConfig" .Values.agents.temporal
)) }}