{{ include "retool.worker.deployment" ( dict 
  "context" . 
  "worker" ( dict 
    "enabled" (include "retool.agents.enabled" .)

    "name" (include "retool.agentWorker.name" .)
    "selectorLabels" (include "retool.agentWorker.selectorLabels" .)
    "workerLabels" (include "retool.agentWorker.labels" .)
    "labels" (.Values.agents.labels | default dict)

    "containerName" "agent-worker"
    "serviceType" "WORKFLOW_TEMPORAL_WORKER"
    "taskqueue" "agent"

    "annotations" (.Values.agents.annotations | default dict)
    "prometheusAnnotations" true

    "healthcheckPort" "3005"
    "metricsPort" "9090"

    "replicaCount" ((.Values.agents.worker).replicaCount | default 1)
    "resources" ((.Values.agents.worker).resources | default .Values.resources)

    "nodeOptions" ((.Values.agents.config).nodeOptions | default "--max_old_space_size=1024")
    "config" (.Values.agents.config | default dict)
    "dbConnectorTimeout" (.Values.agents.dbConnectorTimeout | default (.Values.config.dbConnectorTimeout | default ""))
  )
) }}
