{{ include "retool.worker.deployment" (dict "context" . "worker" (dict 
  "enabled" (include "retool.workflows.enabled" .)
  "name" (include "retool.workflowWorker.name" .)
  "selectorLabels" (include "retool.workflowWorker.selectorLabels" .)
  "labels" (include "retool.workflowWorker.labels" .)
  "containerName" "workflow-worker"
  "serviceType" "WORKFLOW_TEMPORAL_WORKER"
  "replicaCount" ((.Values.workflows.worker).replicaCount | default (.Values.workflows.replicaCount | default 1))
  "resources" .Values.workflows.resources
  "annotations" .Values.workflows.annotations
  "nodeOptions" ((.Values.workflows.config).nodeOptions | default "--max_old_space_size=1024")
  "healthcheckPort" "3005"
  "metricsPort" "9090"
  "prometheusAnnotations" true
  "config" .Values.workflows.config
  "dbConnectorTimeout" .Values.workflows.dbConnectorTimeout
  "temporalConfig" .Values.workflows.temporal
)) }}