{{ include "retool.worker.deployment" (dict "context" . "worker" (dict 
  "enabled" (include "retool.agents.enabled" .)
  "name" (include "retool.agentWorker.name" .)
  "selectorLabels" (include "retool.agentWorker.selectorLabels" .)
  "labels" (include "retool.agentWorker.labels" .)
  "containerName" "agent-worker"
  "serviceType" "WORKFLOW_TEMPORAL_WORKER"
  "taskqueue" "agent"
  "replicaCount" ((.Values.agents.worker).replicaCount | default (.Values.agents.replicaCount | default 1))
  "resources" .Values.agents.worker.resources
  "annotations" .Values.agents.annotations
  "nodeOptions" ((.Values.agents.config).nodeOptions | default "--max_old_space_size=1024")
  "healthcheckPort" "3005"
  "metricsPort" "9090"
  "prometheusAnnotations" true
  "config" .Values.agents.config
  "dbConnectorTimeout" .Values.agents.dbConnectorTimeout
  "temporalConfig" .Values.agents.temporal
)) }}