{{- if and .Values.externalSecrets.externalSecretsOperator.enabled .Values.externalSecrets.externalSecretsOperator.esoVersion }}
{{- range .Values.externalSecrets.externalSecretsOperator.secretRef }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    "helm.sh/hook-weight": "1"
    "helm.sh/hook": pre-install,pre-upgrade
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: {{ .name }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .path }}
---
{{- end }}
{{- end }}
