{{/* We ensure that the jobs runner has highest priority,
since unrun db migrations can lead to pod crashloops. */}}
{{- if not .Values.priorityClassName }}
{{- if include "retool.jobRunner.enabled" . }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "retool.fullname" . }}-jobs-runner-priority
  labels:
    {{- include "retool.labels" . | nindent 4 }}
value: 20
preemptionPolicy: Never
globalDefault: false
description: "PriorityClass for Retool jobs-runner pods"
---
{{- end }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "retool.fullname" . }}-backend-priority
  labels:
    {{- include "retool.labels" . | nindent 4 }}
value: 10
preemptionPolicy: Never
globalDefault: false
description: "PriorityClass for Retool backend pods"
{{- end }}
