externalSecrets:
  enabled: false
  includeConfigSecrets: false
  name: retool-config
  externalSecretsOperator:
    enabled: true
    backendType: secretsManager
    useLegacyCR: false
    secretStoreRef:
      name: retool
      kind: SecretStore
    secretRef:
      - name: retool-config
        path: mysecret
