rr:
  agentSandbox:
    enabled: true
    externalSecret:
      name: agent-sandbox-jwt

mcp:
  enabled: true
  config:
    oauthMainDomain: example.retool.com
    oauthIntrospectionAuthToken: test-oauth-introspection-token
