mcp:
  enabled: true
  replicaCount: 2
  config:
    mcpServiceExternalUrl: https://retool.example.com
    oauthMainDomain: example.retool.com
    agentSandboxJwtPrivateKey: test-agent-sandbox-jwt-private-key
    enabledToolsets:
      - apps
      - resources
    maxTransportSessions: 50
    sessionIdleTimeoutMs: 600000
  environmentVariables:
    - name: MCP_TEST_OPTION
      value: "true"
  service:
    internalPort:

httpRoute:
  enabled: true
