apiVersion: v2
name: retool
description: A Helm chart for Kubernetes
type: application
version: 4.11.7
maintainers:
  - name: Retool Engineering
    email: engineering+helm@retool.com
dependencies:
  - name: postgresql
    version: 10.14.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: retool-temporal-services-helm
    version: 0.18.0
    condition: workflows.enabled
