apiVersion: v2
name: retool
description: A Helm chart for Kubernetes
type: application
version: 4.4.0
appVersion: "2.66.14"
maintainers:
  - name: Retool Engineering
    email: engineering+helm@retool.com
dependencies:
  - name: postgresql
    version: 10.2.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
