codeExecutor:
  enabled: true
  replicaCount: 2
config:
  encryptionKeySecretName: encryption-key
  jwtSecretSecretName: jwt-secret
  postgresql:
    db: retool
    host: dcm-dev-main.cncxzczgbouo.us-west-2.rds.amazonaws.com
    passwordSecretKey: password
    passwordSecretName: db-credentials
    port: 5432
    ssl_enabled: true
    user: retool
  useInsecureCookies: true
dbconnector:
  enabled: true
  replicas: 2
env:
  BASE_DOMAIN: http://dcm-dev.blessed-dev.retool-hosted.com
  IGNORE_CODE_EXECUTOR_STARTUP_CHECK: "true"
externalSecrets:
  enabled: true
  includeConfigSecrets: true
  name: extra-env-vars
image:
  tag: 3.334.0-stable
ingress:
  enabled: false
podDisruptionBudget:
  maxUnavailable: 1
postgresql:
  enabled: false
replicaCount: 2
workflows:
  backend:
    replicaCount: 2
  enabled: true
  worker:
    replicaCount: 2
