{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "retool.fullname" . }}
{{- if or (not .Values.retoolJwtSecret) (not .Values.config.encryptionKey) }}
  labels:
    {{- include "retool.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": no-upgrade-existing
{{- end }}
type: Opaque
data:
  license-key: {{ .Values.config.licenseKey | b64enc | quote }}
  custom_oauth2_sso_client_id: {{ .Values.config.auth.onelogin.customOauth2SsoClientId | b64enc | quote }}
  custom_oauth2_sso_client_secret: {{ .Values.config.auth.onelogin.customOauth2SsoClientSecret | b64enc | quote }}
  custom_oauth2_sso_auth_url: {{ .Values.config.auth.onelogin.customOauth2SsoAuthUrl | b64enc | quote }}
  trigger_oauth_2_sso_login_automatically: {{ .Values.config.auth.onelogin.triggerOauth2SsoLoginAutomatically | b64enc | quote }}
  trigger_saml_login_automatically: {{ .Values.config.auth.onelogin.triggerSamlLoginAutomatically | b64enc | quote }}  

  {{ if .Values.config.jwtSecret }}
  jwt-secret: {{ .Values.config.jwtSecret | b64enc | quote }}
  {{ else  }}
  jwt-secret: {{ randAlphaNum 20 | b64enc | quote }}
  {{ end }}

  {{ if .Values.config.encryptionKey }}
  encryption-key: {{ .Values.config.encryptionKey | b64enc | quote }}
  {{ else  }}
  encryption-key: {{ randAlphaNum 20 | b64enc | quote }}
  {{ end }}

  {{ if .Values.config.auth.google.clientSecret }}
  google-client-secret: {{ .Values.config.auth.google.clientSecret | b64enc |quote }}
  {{ else  }}
  google-client-secret: "" 
  {{ end }}

  {{ if not .Values.postgresql.enabled }}
  postgresql-password: {{ .Values.config.postgresql.password | default "" | b64enc | quote }}
  {{ end }}
{{- end }}